// <auto-generated />
using System;
using BlazorWasmPilet.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWasmPilet.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220626140214_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorWasmPilet.Shared.HealthCarePractitioner", b =>
                {
                    b.Property<int>("PractitionerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PractitionerId"), 1L, 1);

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.HasKey("PractitionerId");

                    b.ToTable("healthCarePractitioners");

                    b.HasData(
                        new
                        {
                            PractitionerId = 1,
                            Designation = "Medical Director",
                            Name = "Sheema Mehboob",
                            ProviderId = 2
                        },
                        new
                        {
                            PractitionerId = 2,
                            Designation = "Physical Therapist",
                            Name = "Danish",
                            ProviderId = 1
                        });
                });

            modelBuilder.Entity("BlazorWasmPilet.Shared.HealthCareProvider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProviderId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProviderId");

                    b.ToTable("healthCareProviders");

                    b.HasData(
                        new
                        {
                            ProviderId = 1,
                            Description = "Baptist HealthCare has everything you need",
                            Name = "Baptist HealthCare",
                            PhoneNumber = "502-111-2222",
                            location = "Lousiville"
                        },
                        new
                        {
                            ProviderId = 2,
                            Description = "UoFL Take cares of your education, health and your well being",
                            Name = "UoFL Health Care",
                            PhoneNumber = "502-111-3333",
                            location = "Lousiville"
                        },
                        new
                        {
                            ProviderId = 3,
                            Description = "Norton's Everything You need",
                            Name = "Norton Health Care",
                            PhoneNumber = "502-111-4444",
                            location = "Lousiville"
                        });
                });

            modelBuilder.Entity("BlazorWasmPilet.Shared.HealthInsuranceInfo", b =>
                {
                    b.Property<int>("InsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceId"), 1L, 1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InsuranceControlId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("InsuranceId");

                    b.ToTable("healthInsuranceInfo");
                });

            modelBuilder.Entity("BlazorWasmPilet.Shared.PatientInfo", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Age = 39,
                            Email = "john.dervik@gmail.com",
                            Gender = "Male",
                            PatientFirstName = "Dervik",
                            PatientLastName = "John",
                            PhoneNumber = "502-123-4567"
                        },
                        new
                        {
                            PatientId = 2,
                            Age = 49,
                            Email = "Kareena.Kapoor@gmail.com",
                            Gender = "Female",
                            PatientFirstName = "Kapoor",
                            PatientLastName = "Kareena",
                            PhoneNumber = "502-123-4568"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
